# Generated by Django 2.2.2 on 2019-06-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intents_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(default='My Trip', max_length=100),
            preserve_default=False,
        ),
    ]
