# Generated by Django 2.2.2 on 2019-06-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intents_app', '0002_trip_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campsite',
            name='campsiteAPI_id',
        ),
        migrations.RemoveField(
            model_name='campsite',
            name='campsite_type',
        ),
    ]
